import { StateGraph, StateSchema, START, END, type GraphNode } from '@langchain/langgraph';
import z from 'zod';
import { GoogleModel, MistralModel, CohereModel } from './model.ai.js';
import { createAgent, HumanMessage, providerStrategy } from 'langchain';

/*
|--------------------------------------------------------------------------
| STATE
|--------------------------------------------------------------------------
|
| State is the shared memory of the graph.
|
| Every node can:
| 1. Read the current state
| 2. Do some work
| 3. Return new values to update the state
|
| Think of it as one object that travels through the whole workflow.
|
*/

const state = new StateSchema({
    // User's question
    problem: z.string().default(''),

    // These will be filled by solutionNode
    solution_1: z.string().default(''),
    solution_2: z.string().default(''),

    // This will be filled by judgeNode
    judge: z.object({
        solution_1_score: z.number().default(0),
        solution_2_score: z.number().default(0),
        solution_1_reasoning: z.string().default(''),
        solution_2_reasoning: z.string().default(''),
    }),
});

/*
|--------------------------------------------------------------------------
| SOLUTION NODE
|--------------------------------------------------------------------------
|
| GraphNode<typeof state>
|
| Means:
| This function works with the state schema defined above.
|
| Every node receives the CURRENT state.
| Every node returns ONLY the values it wants to update.
|
*/

const solutionNode: GraphNode<typeof state> = async (state) => {

    /*
    Current state when this node runs:

    {
        problem: "How to learn Node.js?",
        solution_1: "",
        solution_2: "",
        judge: {}
    }
    */

    /*
    Run both AI models at the same time.
    Promise.all() is faster than waiting for one model and then the other.
    */

    const [mistralResponse, cohereResponse] = await Promise.all([
        MistralModel.invoke(state.problem),
        CohereModel.invoke(state.problem),
    ]);

    /*
    IMPORTANT

    We DO NOT return the whole state.

    We only return the fields that changed.

    LangGraph automatically merges these values into the shared state.
    */

    return {
        solution_1: mistralResponse.text,
        solution_2: cohereResponse.text,
    };
};

/*
|--------------------------------------------------------------------------
| JUDGE NODE
|--------------------------------------------------------------------------
|
| This node runs AFTER solutionNode.
|
| That means it receives the UPDATED state.
|
*/

const judgeNode: GraphNode<typeof state> = async (state) => {

    /*
    Current state now looks something like:

    {
        problem: "...",
        solution_1: "...",
        solution_2: "...",
        judge: {}
    }
    */

    // Extract values from state for easier use
    const { problem, solution_1, solution_2 } = state;

    /*
    Create another AI agent.

    This AI's only job is to judge both solutions.
    */

    const judge = createAgent({
        model: GoogleModel,

        /*
        providerStrategy + zod

        Forces the AI to return JSON in this exact shape.

        Instead of random text like:

        "Solution 1 is better..."

        we get:

        {
            solution_1_score: 8,
            solution_2_score: 9,
            ...
        }
        */

        responseFormat: providerStrategy(
            z.object({
                solution_1_score: z.number().min(0).max(10),
                solution_2_score: z.number().min(0).max(10),
                solution_1_reasoning: z.string(),
                solution_2_reasoning: z.string(),
            })
        ),

        systemPrompt:
            `You are a judge tasked with evaluating two solutions generated by different AI models. Please provide a score out of 10 for each solution, along with your reasoning for the scores.`,
    });

    /*
    Send all information to the judge AI.
    */

    const judgeResponse = await judge.invoke({
        messages: [
            new HumanMessage(`
                Problem: ${problem}
                Solution 1: ${solution_1}
                Solution 2: ${solution_2}

                Please evaluate both solutions.
            `),
        ],
    });

    /*
    Since we forced structured output,
    we can directly access these values.
    */

    const {
        solution_1_score,
        solution_2_score,
        solution_1_reasoning,
        solution_2_reasoning,
    } = judgeResponse.structuredResponse;

    /*
    Again,
    return ONLY the updated part of the state.

    LangGraph merges it automatically.
    */

    return {
        judge: {
            solution_1_score,
            solution_2_score,
            solution_1_reasoning,
            solution_2_reasoning,
        },
    };
};

/*
|--------------------------------------------------------------------------
| BUILD GRAPH
|--------------------------------------------------------------------------
|
| Think of this as creating the workflow.
|
| START
|   |
| solutionNode
|   |
| judgeNode
|   |
| END
|
*/

const graph = new StateGraph(state)

    // Register both nodes
    .addNode('solution', solutionNode)
    .addNode('judge_node', judgeNode)

    // Workflow starts here
    .addEdge(START, 'solution')

    // After solutionNode finishes,
    // run judgeNode
    .addEdge('solution', 'judge_node')

    // Finish graph execution
    .addEdge('judge_node', END)

    // Convert workflow into an executable graph
    .compile();

/*
|--------------------------------------------------------------------------
| RUN GRAPH
|--------------------------------------------------------------------------
|
| graph.invoke()
|
| Starts the workflow from START.
|
| Initial state:
|
| {
|     problem: "user question"
| }
|
| Flow:
|
| START
|   ↓
| solutionNode
|   ↓
| judgeNode
|   ↓
| END
|
| Final state is returned.
|
*/

export default async function runGraph(problem: string) {

    const result = await graph.invoke({
        problem,
    });

    return result;
}